name: "Simple Testing Workflow"


# This is Event
on:
  push:
    branches:
      - main

jobs:
  print_hello:

  #we are using the ubuntu runner here
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello World!"







